const TEAM_TO_CODE: Record<string, string> = {
  Algeria: "dz",
  Angola: "ao",
  Argentina: "ar",
  Australia: "au",
  Austria: "at",
  Bahrain: "bh",
  Belgium: "be",
  "Bosnia and Herzegovina": "ba",
  Brazil: "br",
  Canada: "ca",
  "Cape Verde": "cv",
  Chile: "cl",
  China: "cn",
  Colombia: "co",
  Croatia: "hr",
  Cuba: "cu",
  "Czech Republic": "cz",
  "Curaçao": "cw",
  "DR Congo": "cd",
  Ecuador: "ec",
  Egypt: "eg",
  England: "gb-eng",
  France: "fr",
  Germany: "de",
  Ghana: "gh",
  Guatemala: "gt",
  Haiti: "ht",
  Honduras: "hn",
  Iran: "ir",
  Iraq: "iq",
  "Ivory Coast": "ci",
  Italy: "it",
  Jamaica: "jm",
  Japan: "jp",
  Jordan: "jo",
  Kenya: "ke",
  Mexico: "mx",
  Morocco: "ma",
  Mozambique: "mz",
  Netherlands: "nl",
  "New Zealand": "nz",
  Nigeria: "ng",
  Norway: "no",
  Panama: "pa",
  Paraguay: "py",
  Peru: "pe",
  Poland: "pl",
  Portugal: "pt",
  Qatar: "qa",
  Romania: "ro",
  "Saudi Arabia": "sa",
  Scotland: "gb-sct",
  Senegal: "sn",
  Serbia: "rs",
  "South Africa": "za",
  "South Korea": "kr",
  Spain: "es",
  Sweden: "se",
  Switzerland: "ch",
  Tunisia: "tn",
  Turkey: "tr",
  Uganda: "ug",
  Uruguay: "uy",
  USA: "us",
  Uzbekistan: "uz",
  Wales: "gb-wls",
  "United States": "us",
};

export function getTeamFlagCode(teamName: string): string {
  return TEAM_TO_CODE[teamName] ?? teamName.toLowerCase();
}